"""
New experts by COMPOSITION, with coverage as the percentage.

"An expert with a certain percentage of everything in it" does not mean a
blend -- there is no 30% of ADD, and averaging two rules gives a rule that
answers neither question. What IS well defined is COVERAGE: which atoms of
the shared vocabulary a new expert draws on, as a fraction of the whole.

    coverage  = atoms this expert uses / atoms in the DAG
    novelty   = does it behave unlike every expert already present
    validity  = does it run in all three backends and agree

So a composed expert is generated by picking atoms out of the hash-consed
DAG and wiring them into a new compound. Coverage is then a real percentage
of a real vocabulary, and the expert is kept only if it is behaviourally
new -- the same rule that governs the code index. Growing on coverage alone
would fill the set with rephrasings.
"""
from __future__ import annotations

import itertools
import random
import sys
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from engine.induce import Expr, ev, leaf                        # noqa: E402


def atoms_of(e, acc=None):
    acc = acc if acc is not None else set()
    if e.op == "leaf":
        i, c = e.kids
        acc.add(("leaf", i, c))
    else:
        acc.add((e.op,))
        for k in e.kids:
            if isinstance(k, Expr):
                atoms_of(k, acc)
    return acc


def compose(vocab_ops, vocab_leaves, arity, rng, max_size=6):
    """wire atoms from the shared vocabulary into a new compound"""
    pool = [leaf(f"x{i}", idx=i) for i in range(arity)]
    pool += [leaf(str(c), const=c) for (_, _, c) in vocab_leaves if c is not None]
    if not pool:
        return None
    cur = rng.choice(pool)
    for _ in range(rng.randint(1, max_size)):
        op = rng.choice(sorted(vocab_ops))
        if op in ("neg", "inv"):
            cur = Expr(op, (cur,), f"{'-' if op=='neg' else '1/'}({cur.txt})",
                       cur.size + 1)
        else:
            other = rng.choice(pool)
            sym = "+" if op == "add" else "*"
            cur = Expr(op, (cur, other), f"({cur.txt}{sym}{other.txt})",
                       cur.size + other.size + 1)
    return cur


def behaviour(e, arity, rng, n=60):
    out = []
    for _ in range(n):
        args = [rng.randint(-15, 15) or 2 for _ in range(arity)]
        try:
            out.append(ev(e, args))
        except (ZeroDivisionError, OverflowError, ValueError):
            out.append("ERR")
    return tuple(out)


def grow(dag, originals, arity=3, want=12, seed=5, tries=4000):
    """-> list of new experts, each behaviourally novel, with coverage"""
    rng = random.Random(seed)
    all_atoms = set()
    for e in originals.values():
        all_atoms |= atoms_of(e)
    ops = {a[0] for a in all_atoms if a[0] != "leaf"}
    leaves = {a for a in all_atoms if a[0] == "leaf"}

    # Each original has its OWN arity -- `compound` takes four operands,
    # `meters` one. Evaluating them all at a fixed arity indexed past the
    # end of the argument list. And a behaviour is only comparable at equal
    # arity, so rules of other arities cannot collide with these and are
    # simply not in the baseline.
    def true_arity(e):
        idx = [k[1] for k in atoms_of(e) if k[0] == "leaf" and k[1] is not None]
        return (max(idx) + 1) if idx else 0

    known = set()
    for name, e in originals.items():
        if true_arity(e) == arity:
            known.add(behaviour(e, arity, random.Random(99)))

    out = []
    for _ in range(tries):
        if len(out) >= want:
            break
        e = compose(ops, leaves, arity, rng)
        if e is None:
            continue
        b = behaviour(e, arity, random.Random(99))
        if b in known or all(v == "ERR" for v in b):
            continue
        known.add(b)
        used = atoms_of(e)
        out.append({"expr": e, "size": e.size,
                    "coverage": len(used & all_atoms) / max(len(all_atoms), 1),
                    "atoms": sorted(str(a) for a in used)})
    return out, all_atoms
