"""
Epistemic tagging, and generation restricted to the source's token window.

Facts do not all fail the same way, so they may not be generated the same way:

  DERIVABLE    the answer follows from the question. Generate freely; the
               check catches any error.
  EMPIRICAL    measured. Wrong only if the measurement was wrong.
  CONTINGENT   it happened that way. Could have been otherwise.
  STIPULATED   someone decided. Changes when they decide differently.

The last three are all ASSERTED and none can be derived, but they differ in
how they GO STALE -- a stipulated value changes by decree, a contingent one
never changes but may be misremembered, an empirical one is revised by better
instruments. Tagging them separately is what lets a corpus be audited later.

THE TOKEN WINDOW. For any asserted fact, generation is restricted so that

    the ANSWER is a verbatim span of the source, and
    the QUESTION uses only vocabulary the source contains (plus function
        words), and
    the pair carries the source's epistemic tag.

New phrasings, never new facts. A generated question that reaches outside the
window is rejected, because outside the window there is no source to be
faithful to -- and an answer with no source is the thing this whole system
exists not to produce.
"""
from __future__ import annotations

import re
from collections import Counter

DERIVABLE, EMPIRICAL, CONTINGENT, STIPULATED = (
    "DERIVABLE", "EMPIRICAL", "CONTINGENT", "STIPULATED")

FUNCTION_WORDS = {
    "what", "is", "the", "a", "an", "of", "how", "many", "much", "when",
    "where", "which", "who", "does", "do", "did", "in", "on", "at", "to",
    "for", "and", "or", "was", "were", "are", "be", "been", "has", "have",
    "its", "it", "there", "that", "this", "with", "from", "by", "about",
    "tell", "me", "give", "say", "long", "big", "far", "old", "deep",
    "tall", "high", "wide", "heavy", "fast",
}

CUES = [
    (re.compile(r'\b(law|statute|act|regulation|rule|standard|convention|'
                r'defined as|by definition|agreed|treaty|protocol|iso |si )\b', re.I),
     STIPULATED),
    (re.compile(r'\b(measured|observed|estimated|approximately|about|'
                r'roughly|average|mean|per cent|%|\d+\.\d+)\b', re.I),
     EMPIRICAL),
    (re.compile(r'\b(was|were|founded|named|built|wrote|discovered|formed|'
                r'happened|in \d{4}|ago)\b', re.I),
     CONTINGENT),
]


def tag(text: str) -> str:
    for pat, kind in CUES:
        if pat.search(text):
            return kind
    return EMPIRICAL          # a bare stated quantity is a measurement


def content(s: str) -> set:
    return {w for w in re.findall(r'[a-z0-9]+', s.lower())
            if w not in FUNCTION_WORDS}


def window(source: str) -> set:
    """the vocabulary a generated question may draw on"""
    return content(source)


def admissible(question: str, source: str) -> tuple[bool, str]:
    outside = content(question) - window(source)
    if outside:
        return False, f"question uses {sorted(outside)[:4]} not in the source"
    return True, "within the source's token window"


def spans(source: str, min_words=2):
    """candidate verbatim answers: clauses and sentences of the source"""
    out = []
    for sent in re.split(r'(?<=[.!?])\s+', source):
        sent = sent.strip()
        if not sent:
            continue
        out.append(sent)
        for clause in re.split(r',\s*|;\s*|\s+--\s+', sent):
            clause = clause.strip(" .")
            if len(clause.split()) >= min_words and clause != sent:
                out.append(clause)
    return out


# frames are chosen by the SHAPE of the attribute. "how radius is earth" was
# generated by applying an adjectival frame to a noun -- in-window, faithful,
# and not English. Faithfulness does not make a sentence.
ADJECTIVAL = {"deep", "tall", "high", "old", "big", "wide", "heavy", "fast",
              "far", "hot", "cold", "long", "dense", "bright"}

NOUN_FRAMES = ["what is the {attr} of {subj}",
               "what is {subj}'s {attr}",
               "tell me the {attr} of {subj}"]
ADJ_FRAMES = ["how {attr} is {subj}",
              "what is the {attr}ness of {subj}"]


# some keys name the QUESTION WORD rather than an attribute (bend.where),
# and some name a bare number (speed.70). Forcing a noun frame onto them gave
# "what is the where of bend" and "what is the 70 of speed".
INTERROGATIVE = {"where", "when", "who", "why", "what", "how"}
INT_FRAMES = ["{attr} is {subj}", "{attr} is {subj} located"]


def frames_for(attr):
    if attr in INTERROGATIVE:
        return INT_FRAMES
    if attr in ADJECTIVAL:
        return ADJ_FRAMES
    return NOUN_FRAMES


def frameable(attr) -> bool:
    """a bare number or a code is not an attribute anything can be asked about"""
    return not re.fullmatch(r'[\d_.]+', attr or "")


def generate(key: str, source: str, max_pairs=4):
    """-> [(question, answer_span, tag, why)], all inside the token window.

    Questions are framed from the KEY, which is already semantic
    (earth.radius -> subject `earth`, attribute `radius`), not assembled from
    whatever words the span happens to contain. The first version did the
    latter and produced "what is the answer bryant built" -- faithful, since
    every token came from the source, and useless. Faithfulness and
    usefulness are different properties and the window only buys the first.
    """
    kind = tag(source)
    # THE SOURCE IS THE WHOLE RECORD, not just the gloss. Restricting the
    # window to the English text alone rejected 296 of 350 facts, because a
    # key like `earth.oceandepth` names the attribute and the prose does not
    # repeat it. The key is sourced material too.
    win = window(source) | content(key.replace(".", " "))
    parts = [w for w in re.split(r'[._]', key) if w]
    if len(parts) < 2:
        subj, attr = parts[0], None
    else:
        subj, attr = parts[0], " ".join(parts[1:])
    if attr is None or not frameable(attr):
        return []

    # the span that best answers this key -- most overlap with its words
    want = content(subj + " " + attr)
    # prefer the PRIMARY statement. Scoring by raw overlap picked
    # "The extra 4 minutes to 24h is Earth moving along its orbit" as the
    # answer for `earth.day`, which mentions the topic without stating it.
    best, score = None, -1.0
    sent_list = spans(source)
    for i, sp in enumerate(sent_list):
        ov = len(want & content(sp))
        if ov == 0:
            continue
        # the attribute word itself counts double; earlier spans win ties
        bonus = 1.0 if content(attr) & content(sp) else 0.0
        sc = ov + bonus - 0.01 * i
        if sc > score:
            best, score = sp, sc
    if best is None or score == 0:
        return []
    if best.lower() not in source.lower():
        return []

    out, seen = [], set()
    for f in frames_for(attr):
        q = f.format(subj=subj, attr=attr)
        ok, why = admissible(q, source + " " + key.replace(".", " "))
        if not ok or q in seen:
            continue
        seen.add(q)
        out.append((q, best, kind, why))
        if len(out) >= max_pairs:
            break
    return out
